---
title: "NYC Shootings and Arrests - Data analysis"
author: "Sebastiano Quintavale - 878500"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    html_document:
        toc: true
    pdf_document:
        toc: true
---

```{r}

# Clear preexisting environment
if (!is.null(dev.list())) dev.off()
rm(list = ls())

# Don't display code chunks
knitr::opts_chunk$set(echo = FALSE)

# Load R script sources
source("src/settings.R")
source("src/analysis.R")
source("src/utils.R")
source("src/plot.R")
source("src/time.R")

# Load requirements
load_requirements(REQUIREMENTS)

# Set environment variables
set.seed(SEED)
Sys.setlocale("LC_TIME", LANG)
palette(PALETTE$vibrant)

```

```{r}

# Load data
crimes <- read.csv(FILE_PATHS$NycMonthCrimes)

head(crimes)
summary(crimes)
nrow(crimes)

# Save the names of the crimes (excluding TotArrests)
crime_names <- colnames(crimes)[4:(length(colnames(crimes)) - 2)]
```

```{r}
# Add discrete version for Month and Year
crimes <- discretize(df_=crimes)
head(crimes)
```

```{r}

# Split Train and Test
split       <- train_test_split(df_=crimes, year_test=YEAR_TEST)
crimes      <- split$train
crimes_test <- split$test
rm(split)

summary(crimes)
```

```{r}
# Time series plots

counts <- list()
for (crime_name in c(crime_names, "Shootings")) {

    # Sum by Borough
    crimes_agg <- aggregate(
        crimes[[crime_name]],
        by = list(crimes$Year, crimes$MonthName),
        FUN = sum
    )
    colnames(crimes_agg) <- c("Year", "Month", crime_name)

    counts[[crime_name]] <- df_to_month_ts(crimes_agg, y = crime_name)
}

plot_multiple_ts(
    ts_list = counts,
    title = "Crimes in NYC",
    ylab = "Incidents",
    lwd  = 1
)

# Evidence shootings
lines(
    crimes_agg, type="l", 
    lwd=3, lty='solid', 
    col=get_palette_color(length(crime_names) + 1)
)

rm(counts)

```

```{r}
palette(PALETTE$borough)

for (crime_name in c(crime_names, "TotArrests", "Shootings")) {

    plot_multiple_ts(
        ts_list = lapply(
            split(crimes, crimes$Borough),
            df_to_month_ts,
            y = crime_name
        ),
        title = paste("Crimes in NYC -", crime_name),
        ylab = "Incidents",
        lwd  = 1
    
    )

}


```

```{r}


pca_analysis(
    df_       = crimes,
    features  = c(crime_names, "Shootings"),
    levels    = "Borough",
    title     = "PCA - Crimes in Venice",
    highligth = c("Shootings")
)   

pca_analysis(
    df_       = crimes[crimes$Borough != "Queens", ],
    features  = c(crime_names, "Shootings"),
    levels    = "Borough",
    title     = "PCA - Crimes in NYC",
    highligth = c("Shootings")
)

```

```{r}
# Plots
for (time in c("Year", "Month")) {
    levels_scatterplot(
        df_     = crimes,
        x       = time,
        y       = "Shootings",
        levels  = "Borough",
        title   = paste("Boroughs - Shootings by", time),
        jitter_ = TRUE
    )
}

for (crime in crime_names) {
    levels_scatterplot(
        df_     = crimes,
        x       = crime,
        y       = "Shootings",
        levels  = "Borough",
        title   = paste("Boroughs - Shootings vs ", crime),
        jitter_ = TRUE
    )
}
```

```{r}
# Extract outliers
crimes[
    crimes$TotArrests < 2000 &
    crimes$Shootings > 100,
]
```

```{r}

# Set up the plotting area with a 3x5 layout
{ par(mfrow = c(3, 5), oma = c(0, 0, 2, 0)) # oma adds outer margins

for (borough in levels(crimes$Borough)) {
    df_ <- crimes[crimes$Borough == borough, ]
    plot_feature_ccf(df_, crime_names, "Shootings")
    # Add an overall title to the entire plot
    mtext(
        paste("CCF Analysis of Shootings in ", borough), 
        outer = TRUE, cex = 1.5
    )
}

par(mfrow = c(1, 1)) }

```
