---
title: "NYC Shootings and Arrests - Data analysis"
author: "Sebastiano Quintavale - 878500"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: tango
---

```{r echo=FALSE, include=FALSE}

# 1. RMardown styling
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width = 12, fig.height = 8)

# 2. Project environment setup
source("src/init.R")

```

```{r}

# Load data
crimes <- read.csv(PATHS$NycMonthCrimes)

```
```{r}

# Add discrete version for Month and Year
crimes <- prepare_crimes(crimes_df=crimes)

crime_names <- colnames(crimes)[4:17]


# Split Train and Test
split <- train_test_split_by_year(df_ = crimes, year_test = YEAR_TEST)
crimes <- split$train
crimes_test <- split$test
rm(split)

summary(crimes)
```

```{r}
# Take apart Queens from the borough and recompute the total

split_out <- split_statenisland(crimes=crimes, crimes_test=crimes_test)

crimes         <- split_out$crimes
crimes_test    <- split_out$crimes_test
si_crimes      <- split_out$si_crimes
si_crimes_test <- split_out$si_crimes_test
```

## State Staten

```{r}

plot(si_crimes)

# Arrange the plots in a 2x3 grid
grid.arrange(
    grobs = lapply(
        c("Year", "Month", "Murder", "Assaults", "Robbery", "TotArrests"),
        function(element) {
            basic_scatterplot(
                x = element,
                y = "Shootings",
                data = si_crimes,
                jitter_ = TRUE,
                title = element,
                size = 1.5
            )
        }
    ), 
    top = grid::textGrob(
        "StatenInsland - Criminality and time impact on Shootings",
        gp = grid::gpar(fontsize = 16, fontface = "bold")
    ),
    ncol = 3
)

df_group_stats(si_crimes, "Year", "Shootings")

df_group_stats(si_crimes, "Month", "Shootings")

#knitr::kable(stats_table, format = "html") %>%
#    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F)

# Time relations

plot_ts(
    df_ts = ts_crimes_reshape(si_crimes),
    group = "CrimeType",
    y     = "Shootings",
    ylab  = "Shootings",
    title = "Shootings in StatenIsland",
    lwd   = 0.7
) +
    geom_hline(yintercept = mean(si_crimes$Shootings), linetype = "dashed", color = "#124ecfdf", linewidth = 0.5)

plot_ts_stl_decomposition(
    df_ = si_crimes,
    y = "Shootings",
    title = "Shootings in StatenIsland"
)
```

```{r}
# Linear models
si_crimes_models <- list()

# Null model predicting the mean level
si_crimes_models$null <- lm(Shootings ~ 1, data = si_crimes)
lm_diagnostic(
    si_crimes_models$null, 
    residuals = FALSE, 
    effects   = FALSE,
    vif       = FALSE
)

si_crimes[c(10, 43), c("Year", "Month", "Shootings")]

# Using month levels with constraints they sum up to 0
contrasts(si_crimes     $MonthName) <- contr.sum(12)
contrasts(si_crimes_test$MonthName) <- contr.sum(12)

si_crimes_models$month <- lm(
    Shootings ~ MonthName, 
    data = si_crimes
)

lm_diagnostic(
    si_crimes_models$month, 
    influencial_points = FALSE,
    effects = FALSE,
    vif = FALSE
)

plot_model_coefficients(
    coefs  = si_crimes_models$month$coefficients[2:12],
    xlab   = "Month",
    title  = "StatenIsland Month Coefficients",
    labels = month.abb
)

# Using arrests and murders
si_crimes_models$totarrests <- lm(
    Shootings ~ TotArrests,
    data = si_crimes
)

lm_diagnostic(
    si_crimes_models$totarrests, 
    effects = FALSE, 
    influencial_points = FALSE,
    vif = FALSE
)

si_crimes_models$totarrests2 <- lm(
    Shootings ~ TotArrests + I(TotArrests^2),
    data = si_crimes
)

lm_diagnostic(
    si_crimes_models$totarrests2,
    influencial_points = FALSE,
    vif = FALSE,
    effects = FALSE
)


si_crimes_models$totarrests3 <- lm(
    Shootings ~ TotArrests + I(TotArrests^2) + I(TotArrests^3),
    data = si_crimes
)
lm_diagnostic(
    si_crimes_models$totarrests3,
    influencial_points = FALSE,
    vif = FALSE,
    effects = FALSE
)

plot_multiple_model_prediction(
    df_=si_crimes,
    models=list(
                linear = si_crimes_models$totarrests,
                square = si_crimes_models$totarrests2,
                cubic  = si_crimes_models$totarrests3
            ),
    x="TotArrests", y="Shootings", 
    title="AAAAAAAA",
    ylab ="BBBBBBb",
    jitter_=TRUE
)


models=list(
    linear = si_crimes_models$totarrests,
    square = si_crimes_models$totarrests2,
    cubic  = si_crimes_models$totarrests3
)

generate_prediction_table(
    models = list(
        linear = si_crimes_models$totarrests,
        square = si_crimes_models$totarrests2,
        cubic  = si_crimes_models$totarrests3
    ),
    predictor_name = "TotArrests",
    predictor_values = seq(1000, 10000, 1000)
)


si_crimes_models$crimes <- lm(
    Shootings ~ Murder + Robbery,
    data = si_crimes,
)

lm_diagnostic(
    si_crimes_models$crimes,
    influencial_points = FALSE,
    effects = FALSE
)

# Select the best model using step subset selection leaps library
subset_regression_info(
    subset_reg = regsubsets(
        Shootings ~ . - TotArrests - Month - SqrtTotArrests,
        data = si_crimes,
        nvmax = 21
    )
)

# Select the regsubsets model with 4 predictors
si_crimes_models$auto <- lm(
    Shootings ~ Mischief + Murder +
        as.numeric(MonthName == "Feb") +
        as.numeric(MonthName == "Jul"),
    data = si_crimes
)

lm_diagnostic(
    si_crimes_models$auto,
    effects = FALSE,
    influencial_points = FALSE
)

```

```{r}

for (df_ in list(si_crimes, si_crimes_test)) {

    models_stats <- get_models_prediction_stats(
        models = si_crimes_models,
        df_ = df_,
        y = "Shootings"
    )

    print(
        stats_to_table(models_stats)
    )

    plot_multiple_model_predictions_over_time(
        df_ = df_,
        models_stats = models_stats,
        y = "Shootings",
        title = "Shootings in Queens - Test set predictions",
        ylab = "Shootings count",
        ci = TRUE,
        lwd = 1,
        ticks = 3,
        lwd_observations = 0.5,
        grid_rows=4
    )

}
```


```{r}
# Create multiple time series for each different borough in crimes

plot_multiple_ts(
    df_ts = ts_borough_reshape(
        df_ = crimes[, c("Borough", "Year", "MonthName", "Shootings")],
        crime_type = "Shootings"
    ),
    group = "Borough",
    xlab = "Year",
    ylab = "Incidents",
    title = paste("Shootings in NYC"),
    lwd = 0.7,
    colors = unlist(PALETTE$boroughs)
)

palette_outlier <- PALETTE$outliers

plots <- list()

for(borough in levels(crimes$Borough)) {

    palette_outlier$ts <- PALETTE$boroughs[[borough]]

    outliers_out <- outliers_diagnostic(
        df_ = crimes[crimes$Borough == borough,],
        y = "Shootings",
        colors = palette_outlier,
        title = borough,
        ylab = "Shootings incidents"
    )

    plots[[borough]] <- outliers_out$plot
    

    crimes <- replace_outliers(
        df_=crimes,
        y = "Shootings",
        outliers = outliers_out$outliers,
        level=borough
    )

}

grid.arrange(grobs=plots, ncol=2)

plot_multiple_ts(
    df_ts = ts_borough_reshape(
        df_ = crimes[, c("Borough", "Year", "MonthName", "Shootings")],
        crime_type = "Shootings"
    ),
    group = "Borough",
    xlab = "Year",
    ylab = "Incidents",
    title = paste("Shootings in NYC"),
    lwd = 0.7,
    colors = unlist(PALETTE$boroughs)
)


```


```{r}

plot_ccf_grid(
    df    = crimes,
    y     = "Shootings",
    level = "Borough"
)
```

```{r}
for (borough in unique(crimes$Borough)) {
    df_ <- crimes[crimes$Borough == borough, ]

    plot_ts_stl_decomposition(
        df_ = df_, y = "Shootings", title = paste(borough, "- STL Decomposition")
    )
}
```

```{r}
levels_scatterplot(
    df_ = crimes,
    x = "Month",
    y = "Shootings",
    levels = "Borough",
    title = "Shootings during year across Boroughs",
    jitter_ = TRUE,
    colors = unlist(PALETTE$boroughs)
)

models <- list()
```

```{r}

# Fit a quadratic model with different coefficients for each borough
contrasts(crimes     $MonthName) <- contr.sum(12)
contrasts(crimes_test$MonthName) <- contr.sum(12)
contrasts(crimes     $Borough)   <- contr.sum (4)
contrasts(crimes_test$Borough)   <- contr.sum (4)

models$month_steps <- lm(
    Shootings ~ MonthName * Borough,
    data = crimes
)

lm_diagnostic(
    models$month_steps,
    vif = FALSE,
    influencial_points = FALSE
)

plot_model_predictions_per_level_over_time(
    model = models$month_steps,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
)

plot_model_predictions_per_level_over_time(
    model = models$month_steps,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
)
```





```{r}
# Add time indicator
get_epoch <- function(year, month) {
    (year - min(crimes$Year)) * 12 + month
}

crimes$t <- get_epoch(year = crimes$Year, month = crimes$Month)
crimes_test$t <- get_epoch(year = crimes_test$Year, month = crimes_test$Month)

models$periodic <- lm(
    Shootings ~ t + I(t^2) + I(t^3) + sin(2 * pi * t / 12) + cos(2 * pi * t / 12) + Borough,
    data = crimes
)

lm_diagnostic(
    models$periodic, 
    effects = FALSE,
    vif = FALSE,
    influencial_points = FALSE
)

plot_model_predictions_per_level_over_time(
    model = models$periodic,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
)

plot_model_predictions_per_level_over_time(
    model = models$periodic,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
)


```

```{r}
models$totarrests2 <- lm(
    Shootings ~ TotArrests +I(TotArrests^2),
    data = crimes
)

models$totarrests3 <- lm(
    Shootings ~ TotArrests +I(TotArrests^2) + I(TotArrests^3),
    data = crimes
)

lm_diagnostic(
    models$totarrests2,
    effects=FALSE, vif=FALSE, influencial_points=FALSE
)

lm_diagnostic(
    models$totarrests3,
    effects=FALSE, vif=FALSE, influencial_points=FALSE
)

plot_multiple_model_prediction(
    df_=crimes,
    x = "TotArrests",
    y = "Shootings",
    models = list(
        Quadratic = models$totarrests2,
        Cubic     = models$totarrests3
    ),
    jitter_=TRUE
)

plot_multiple_model_prediction(
    df_=crimes_test,
    x = "TotArrests",
    y = "Shootings",
    models = list(
        Quadratic = models$totarrests2,
        Cubic     = models$totarrests3
    ),
    jitter_=TRUE
)

```

```{r}
models$totarrests_borough <- lm(
    Shootings ~ TotArrests + I(TotArrests^2) + Borough,
    data = crimes
)

lm_diagnostic(
     models$totarrests_borough,
     effects=FALSE, vif=FALSE, influencial_points=FALSE
)

plot_model_prediction_per_level(
    model  = models$totarrests_borough,
    df_    = crimes,
    x      = "TotArrests",
    y      = "Shootings",
    levels = "Borough",
    title  = "Shootings in Borough - Training set",
    ylab   = "Shootings incidents",
)

plot_model_prediction_per_level(
    model  = models$totarrests_borough,
    df_    = crimes_test,
    x      = "TotArrests",
    y      = "Shootings",
    levels = "Borough",
    title  = "Shootings in Borough - Test set",
    ylab   = "Shootings incidents"
)

plot_model_predictions_per_level_over_time(
    model = models$totarrests_borough,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    grid_rows = 2
)

plot_model_predictions_per_level_over_time(
    model = models$totarrests_borough,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    grid_rows = 2
)
```

```{r}
# Shrinkage selection
predictors <- c(crime_names, "Year", "MonthName")

# Create an empty data frame to store the results
# summary_df <- data.frame(Borough = levels(crimes$Borough), stringsAsFactors = FALSE)
# 
# shrinkage_on_borough <- function(df_, y, type, title) {
#     
#     sub <- crimes[
#         crimes$Borough == borough,
#         c(predictors, "Shootings")
#     ]
# 
#     # Create a list to store the results for each type
#     results <- list()
# 
#     for (type in c("min", "1se")) {
#         model_out <- shrinkage_selection(
#             df_ = sub,
#             y = "Shootings",
#             type = type,
#             title = paste("Lasso selection for", borough, "borough")
#         )
# 
#         print(paste("BOROUGH", borough, "TYPE", type))
#         print(coef(model_out))
# 
#         # Store the number of predictors in the results list
#         results[[type]] <- sum(coef(model_out) != 0)
#     }
# 
#     # Add the results to the summary data frame
#     summary_df[summary_df$Borough == borough, c("min", "1se")] <- unlist(results)
# 
# }
```


```{r}
for (type in c("min", "1se")) {
    model_name <- paste("lasso_", type, sep = "")

    model_out <- shrinkage_selection(
        df_ = crimes[, c(predictors, "Borough", "Shootings")],
        y = "Shootings",
        type = type,
        title = paste("Lasso selection for NYC -", type)
    )

    print(type)

    print(coef(model_out))
    print(paste("Predicotrs", sum(coef(model_out) != 0)))

    models[[model_name]] <- model_out
}

```

```{r}

plot_model_predictions_per_level_over_time(
    model = models$lasso_min,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    glmnet_predictors = c(predictors, "Borough"),
    colors = unlist(PALETTE$boroughs),
    grid_rows=2
)

plot_model_predictions_per_level_over_time(
    model = models$lasso_min,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings in Borough - Training set",
    ylab = "Shootings incidents",
    ci = TRUE,
    glmnet_predictors = c(predictors, "Borough"),
    colors = unlist(PALETTE$boroughs),
    grid_rows=2
)

```

```{r}

models_stats <- get_models_prediction_stats(
    models = models,
    df_ = crimes,
    y = "Shootings",
    glmnet_predictors = c(predictors, "Borough")
)
out_table <- stats_to_table(models_stats)
out_table


kable(out_table, format = "html") %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F)
```




