---
title: "NYC Shootings and Arrests - Data analysis"
author: "Sebastiano Quintavale - 878500"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: tango
---

```{r echo=FALSE, include=FALSE}

# 1. RMardown styling
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width = 12, fig.height = 8)

# 2. Project environment setup
source("src/init.R")

```



```{r}

# Load data
crimes <- read.csv(PATHS$NycMonthCrimes)

crimes <- prepare_crimes(crimes_df=crimes)

crime_names <- colnames(crimes)[4:17]


# Split Train and Test
split <- train_test_split_by_year(df_ = crimes, year_test = YEAR_TEST)
crimes      <- split$train
crimes_test <- split$test
rm(split)

# Take apart Queens from the borough and recompute the total

split_out <- split_statenisland(crimes=crimes, crimes_test=crimes_test)

crimes         <- split_out$crimes
crimes_test    <- split_out$crimes_test
si_crimes      <- split_out$si_crimes
si_crimes_test <- split_out$si_crimes_test

# Outliers

for(borough in levels(crimes$Borough)) {

    outliers_out <- outliers_diagnostic(
        df_ = crimes[crimes$Borough == borough,],
        y = "Shootings", colors = PALETTE$outliers
    )

    crimes <- replace_outliers(
        df_=crimes,
        y = "Shootings",
        outliers = outliers_out$outliers,
        level=borough
    )

}
```

## Poisson Model

### Seasonal model

```{r}

# Add constrast
contrasts(crimes     $MonthName) <- contr.sum(12)
contrasts(crimes_test$MonthName) <- contr.sum(12)

pois_models <- list()

tapply(crimes$Shootings, crimes$Borough, mean)
tapply(crimes$Shootings, crimes$Borough, var)

pois_models$seasonality <- glm(
    Shootings ~ Borough + MonthName,
    data = crimes,
    family = "poisson"
)

# TODO - Chiedere al colloquio perché non si può
# https://stats.stackexchange.com/questions/418832/why-the-absence-of-probability-distribution-for-using-quasi-likelihood
AIC(pois_models$seasonality)

glm_diagnostic(
    model = pois_models$seasonality, 
    df_ = crimes, 
    gvif = FALSE,
    residuals = TRUE,
    overdispersion = FALSE
)

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$seasonality,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Month seasonal model - Training set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
))

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$seasonality,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Month seasonal model - Test set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
))

```

### Trended model

```{r}

pois_models$trended <- glm(
    Shootings ~ Borough + MonthName + Year,
    data = crimes,
    family = poisson
)

glm_diagnostic(
    model=pois_models$trended, 
    df_=crimes,
    gvif=TRUE, overdispersion=FALSE
)

pois_models$trended <- NULL

pois_models$trended2 <- glm(
    Shootings ~ Borough + MonthName + poly(Year, 3),
    data = crimes,
    family = poisson
)

glm_diagnostic(
    model=pois_models$trended2, 
    df_=crimes,
    gvif=FALSE, 
    overdispersion=FALSE
)


invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$trended2,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Trended model - Training set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
))

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$trended2,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Trended model - Test set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
))
```

```{r}
# Good for short-term prediction. Compare with others

crimes_time      <- crimes
crimes_time_test <- crimes_test

crimes_time$t      <- get_epoch(year = crimes_time     $Year, month = crimes_time     $Month)
crimes_time_test$t <- get_epoch(year = crimes_time_test$Year, month = crimes_time_test$Month)

linear_trend <- lm(
    Shootings ~ t + I(t^2) + I(t^3) + sin(2 * pi * t / 12) + cos(2 * pi * t / 12) + Borough,
    data = crimes_time
)

# First term test
MONTHS <- 3
first_test_epoch <- min(crimes_time_test$t)
short_term_test <- crimes_time_test[
    crimes_time_test$t > first_test_epoch &
    crimes_time_test$t < first_test_epoch + MONTHS,
]

class(pois_models$trended2)

# Get prediction table
stats_to_table(
    stats = get_models_prediction_stats(
        models = list(
            Poisson = pois_models$trended2,
            Linear  = linear_trend
        ),
        df_ = short_term_test,
        y = "Shootings"
))[, c(-1, -2)]

rm(list = c(
    "crimes_time", "crimes_time_test", "linear_trend", 
    "first_test_epoch", "short_term_test", "MONTHS"
))


```
### Total Arrests model
```{r}
pois_models$totarrests <- glm(
    Shootings ~ Borough + TotArrests + I(TotArrests^2),
    data = crimes, family = "poisson"
)

glm_diagnostic(
    pois_models$totarrests, df_=crimes,
    gvif=FALSE, overdispersion = FALSE
)

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$totarrests,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Total arrests model - Training set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
))

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$totarrests,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Total arrests model - Test set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    grid_rows = 2
))

```

### Shrinkage for crimes across boroughs

```{r}
SHRINKAGE_PREDICTORS <- c(crime_names, "Year", "MonthName", "TotArrests")
COL = "(1se, alpha=1)"

out_cols <- list()

for(borough in levels(crimes$Borough)) {

    print(paste("Borough crimes Shrinkage: ", borough))
    out <- shrinkage_grid_search(
        df_ = crimes[
            crimes$Borough == borough, 
            c(SHRINKAGE_PREDICTORS, "Shootings")
        ], 
        y="Shootings", 
        alphas=c(0, 1)
    )

    print(out)

    colnames(out)

    out_cols[[borough]] <- out[, c(COL)]

    print("")

}

{
out_df <- round(as.matrix(do.call(rbind, out_cols)), 3)
colnames(out_df) <- rownames(out)
out_df[out_df == 0] <- "."
out_df <- as.data.frame(t(out_df), stringsAsFactors = FALSE)
out_df
}

knit_table(out_df)

rm("out_df", "COL", "out_cols")
```

### Shrinkage model

```{r}
coef(lm(Shootings ~ ., data = crimes[, c(SHRINKAGE_PREDICTORS, "Shootings")]))

```

```{r}

SHRINKAGE_PREDICTORS <- c(SHRINKAGE_PREDICTORS, "Borough")

shrinkage_grid_search(
    df_ = crimes[, c(SHRINKAGE_PREDICTORS, "Shootings")], 
    y="Shootings", 
    alphas=c(0, 1)
)

```

```{r}
pois_models$lasso <- shrinkage_selection(
    df_ = crimes[, c(SHRINKAGE_PREDICTORS, "Shootings")],
    y = "Shootings",
    type = "1se",
    alpha = 1,
    title = paste("Lasso selection for NYC"),
    family="poisson"
)

```

```{r}

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$lasso,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Lasso model - Training set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    glmnet_predictors = SHRINKAGE_PREDICTORS,
    grid_rows = 2
))

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$lasso,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Lasso model - Test set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    glmnet_predictors = SHRINKAGE_PREDICTORS,
    grid_rows = 2
))

```

### Stepwise model

```{r}
stepwise_model <- step(
    glm(
        Shootings ~ .,
        data = crimes[, c("Shootings", SHRINKAGE_PREDICTORS)],
        family = poisson
    ),
    scope = list(lower = ~1, upper = ~.),
    direction = "both",
    trace = 0,
    k = log(nrow(crimes)) # BIC
)

summary(stepwise_model)

vif_diagnostic(stepwise_model)

```


### Crimes model
```{r}
pois_models$crimes <- glm(
    Shootings ~ Borough + Bribery + SubstancePossession + MonthName,
    data = crimes, family = "poisson"
)

glm_diagnostic(
    pois_models$crimes, df_=crimes,
    gvif=TRUE, overdispersion = FALSE
)

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$crimes,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Crimes model - Training set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    glmnet_predictors = SHRINKAGE_PREDICTORS,
    grid_rows = 2
))

invisible(plot_model_predictions_per_level_over_time(
    model = pois_models$crimes,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Crimes model - Test set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    glmnet_predictors = SHRINKAGE_PREDICTORS,
    grid_rows = 2
))

```

### Model comparison

```{r}
pois_models$borough_mean <- glm(Shootings ~ Borough, data=crimes, family = "poisson")
```

```{r}
models_stats <- get_models_prediction_stats(
    models = pois_models,
    df_ = crimes_test,
    y = "Shootings",
    glmnet_predictors = SHRINKAGE_PREDICTORS
)
out_table <- stats_to_table(models_stats)[, -c(1, 2)]
out_table

```

## Comparison with other Counting Models

```{r}
model.pois <- glm(
    Shootings ~ Borough + Bribery + SubstancePossession + MonthName,
    data = crimes, family = "poisson"
)

```

### Quasi-poisson

```{r}
model.quasipois <- glm(
    Shootings ~ Borough + Bribery + SubstancePossession + MonthName,
    data = crimes, family = "quasipoisson"
)

summary(model.pois)
summary(model.quasipois)

(summary(model.quasipois))$dispersion
```


```{r}

invisible(plot_model_predictions_per_level_over_time(
    model = model.quasipois,
    df_ = crimes,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Quasipoisson - Training set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    glmnet_predictors = SHRINKAGE_PREDICTORS,
    grid_rows = 2
))

invisible(plot_model_predictions_per_level_over_time(
    model = model.quasipois,
    df_ = crimes_test,
    y = "Shootings",
    levels = "Borough",
    title = "Shootings per Borough - Quasipoisson - Test set",
    ylab = "Shootings incidents",
    level = LEVEL,
    lwd = 0.5,
    lwd_observations = 0.5,
    colors = unlist(PALETTE$boroughs),
    glmnet_predictors = SHRINKAGE_PREDICTORS,
    grid_rows = 2
))

```

### Negative Binomial

```{r}

model.nb <- glm.nb(
    Shootings ~ Borough + Bribery + SubstancePossession + MonthName,
    data = crimes
)

summary(model.nb)


coef(model.nb)[2:4]
coef(model.pois)[2:4]

coef(model.nb)[5:6]
coef(model.pois)[5:6]

coef(model.nb)[7:17]
coef(model.pois)[7:17]

```

### GAM

```{r}
model.gam_pois <- gam(
    Shootings ~ Borough + s(Bribery) + s(SubstancePossession) + MonthName,
    data = crimes,
    family = poisson
)

model.gam_nb <- gam(
    Shootings ~ Borough + s(Bribery) + s(SubstancePossession) + MonthName,
    data = crimes,
    family = nb
)

summary(model.gam_pois)
summary(model.gam_nb)

```

### Comparison

```{r}
AIC(model.pois, model.nb, model.gam_pois, model.gam_nb)
BIC(model.pois, model.nb, model.gam_pois, model.gam_nb)
```

```{r}

models_stats <- get_models_prediction_stats(
    models = list(
        Pois    = model.pois,
        QPois   = model.quasipois,
        NegBin  = model.nb,
        GAMPois = model.gam_pois,
        GAMNb   = model.gam_nb
    ),
    df_ = crimes_test,
    y = "Shootings",
    glmnet_predictors = SHRINKAGE_PREDICTORS
)
out_table <- stats_to_table(models_stats)[, -c(1, 2)]
out_table

```



